//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ScorpiusMain
{
    [Serializable]
    public class TeleopMsg : Message
    {
        public const string k_RosMessageName = "scorpius_main/Teleop";
        public override string RosMessageName => k_RosMessageName;

        public float posx;
        public float posy;
        public float posz;

        public TeleopMsg()
        {
            this.posx = 0.0f;
            this.posy = 0.0f;
            this.posz = 0.0f;
        }

        public TeleopMsg(float posx, float posy, float posz)
        {
            this.posx = posx;
            this.posy = posy;
            this.posz = posz;
        }

        public static TeleopMsg Deserialize(MessageDeserializer deserializer) => new TeleopMsg(deserializer);

        private TeleopMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.posx);
            deserializer.Read(out this.posy);
            deserializer.Read(out this.posz);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.posx);
            serializer.Write(this.posy);
            serializer.Write(this.posz);
        }

        public override string ToString()
        {
            return "TeleopMsg: " +
            "\nposx: " + posx.ToString() +
            "\nposy: " + posy.ToString() +
            "\nposz: " + posz.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
